repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
        files: 'core2/.*$'
      # Run the formatter.
      - id: ruff-format
        files: 'core2/.*$'
